name: Master_Publish_Terraform_Module

on:
   push:
     branches:
       - master
     paths-ignore:
       - '.gitignore'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Checkout Master Branch, Bumps the Tag Version and Create a Release'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: Bump Version and Push Tag
      id: create_tag
      uses: anothrNick/github-tag-action@1.22.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: master
        INITIAL_VERSION: 1.0.0
        WITH_V: true
        DEFAULT_BUMP: minor

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: Release ${{ steps.create_tag.outputs.tag }}
        draft: false
        prerelease: false